

name: "Close stale issues"
on:
  schedule:
  - cron: "* * * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: szenius/notion-burndown@3.0.0
      with:
        NOTION_KEY: "secret_DdZhIErI9nREy90OLHFkr7WKO6GNYEGu8luaBxqw4Hf"
        NOTION_DB_BACKLOG: "10fa492ea47245cfaf86ccd7d188fd7a"
        NOTION_DB_SPRINT_SUMMARY: "40f4d477aa5e4578a97f9f38e1aaa0c6"
        NOTION_DB_DAILY_SUMMARY: "bbdf48e80d4f49fdb68de68defb3daee"
        NOTION_PROPERTY_SPRINT: "Name of the property with the sprint number"
        NOTION_PROPERTY_ESTIMATE: "Name of the property with the estimate"
        NOTION_PROPERTY_PATTERN_STATUS_EXCLUDE: "Regex of the statuses of stories which are done"
        INCLUDE_WEEKENDS: "True if weekends should be included in the chart, false otherwise."
        SPRINT_START: "True if it is the start of a new sprint, false otherwise. "
